name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
    
concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  # See https://github.com/git-lfs/git-lfs/issues/5749
  GIT_CLONE_PROTECTION_ACTIVE: 'false'

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            name: "Ubuntu 24.04"
    steps:
      - name: Setup Pragma
        uses: Silverlan/tmp_UniRender_Cycles3/github_actions/setup@main
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build Dependencies
        uses: Silverlan/pragma/github_actions/build@main
        id: build-deps
        with:
          # This will build the core dependencies, as well as cycles, but not Pragma
          build-args: "--with-essential-client-modules=0 --with-common-modules=0 --with-lua-debugger=0 --module pr_unirender:\"https://github.com/Silverlan/pr_cycles.git\" --build 0 --build-cycles"

      - name: Build UniRender_cycles
        shell: bash
        run: |
          root="$PWD"
          cd "${{ steps.build-deps.outputs.build-dir }}"
          cmake --build "." --config "RelWithDebInfo" --target UniRender_cycles
          
          cd $root
          mkdir -p release/modules/unirender/cycles
          releaseDir="$root/release"
          pragmaDir="${{ steps.build-deps.outputs.root-dir }}"
          depsDir="${{ steps.build-deps.outputs.deps-dir }}"
          buildDir="${{ steps.build-deps.outputs.build-dir }}"
          cyclesDir="$releaseDir/modules/unirender/cycles"

          echo "ALL FILES IN pragmaDir: $pragmaDir"
          cd $pragmaDir
          ls -R

          echo "ALL FILES IN depsDir: $depsDir"
          cd $depsDir
          ls -R

          echo "ALL FILES IN buildDir: $buildDir"
          cd $buildDir
          ls -R

          echo "ALL FILES IN cyclesDir: $cyclesDir"
          cd $cyclesDir
          ls -R
          
          copy_binary () {
             cmake -DInstallSrc="$1" -DInstallDst="$cyclesDir/" -P $pragmaDir/build_scripts/cmake/install_file.cmake
          }
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_atomic.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_chrono.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_date_time.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_filesystem.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_regex.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_serialization.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_system.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_thread.so"
          copy_binary "$depsDir/boost_1_81_0/stage/lib/libboost_wave.so"
          copy_binary "$depsDir/cycles/install/lib/libIex.so"
          copy_binary "$depsDir/cycles/install/lib/libIlmThread.so"
          copy_binary "$depsDir/cycles/install/lib/libImath.so"
          copy_binary "$depsDir/cycles/install/lib/libOpenColorIO.so"
          copy_binary "$depsDir/cycles/install/lib/libOpenEXR.so"
          copy_binary "$depsDir/cycles/install/lib/libOpenEXRCore.so"
          copy_binary "$depsDir/cycles/install/lib/libOpenEXRUtil.so"
          copy_binary "$depsDir/cycles/install/lib/libOpenImageIO.so"
          copy_binary "$depsDir/cycles/install/lib/libOpenImageIO_Util.so"
          copy_binary "$depsDir/cycles/install/lib/libopenvdb.so"
          copy_binary "$depsDir/cycles/install/lib/liboslcomp.so"
          copy_binary "$depsDir/cycles/install/lib/liboslexec.so"
          copy_binary "$depsDir/cycles/install/lib/liboslnoise.so"
          copy_binary "$depsDir/cycles/install/lib/liboslquery.so"
          copy_binary "$buildDir/modules/pr_unirender/external_libs/cycles/RelWithDebInfo/libUniRender_cycles.so"
          
          mkdir -p "$cyclesDir/source"
          cp -r "$depsDir/cycles/src/kernel" "$cyclesDir/source/kernel"
          cp -r "$depsDir/cycles/src/util" "$cyclesDir/source/util"
          
          # We're using " 2>/dev/null || :" to ignore errors if the files don't exist
          cp $depsDir/cycles/build/src/kernel/*.ptx "$cyclesDir/source/kernel/" 2>/dev/null || :
          cp $depsDir/cycles/build/src/kernel/*.cubin "$cyclesDir/source/kernel/" 2>/dev/null || :

      - name: Copy render_raytracing files
        shell: bash
        run: |
          mkdir -p "release/lib"
          cp "${{ steps.build-deps.outputs.install-dir }}/lib/librender_raytracing_lib.so" "release/lib" || true
          cp "${{ steps.build-deps.outputs.install-dir }}/lib/render_raytracing" "release/lib" || true
          cp "${{ steps.build-deps.outputs.install-dir }}/lib/libutil_raytracing.so" "release/lib" || true
          cp "${{ steps.build-deps.outputs.install-dir }}/lib/libOpenColorIO*" "release/lib" || true
          cp "${{ steps.build-deps.outputs.install-dir }}/lib/libOpenImageDenoise*" "release/lib" || true

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
